
circle-ci-props:
  orbs:
    node: circleci/node@5.2.3

jobs:
  - package-2-build:
      just-depends-on-type: build
      working_directory: ~/package_2
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Build package-2
            command: just build


workflow:
  build:
    just-depends-on-type: build
    jobs:
      - package-2-build:
          context:
            - context-2
            - slack-context
