version: 3.1

parameters:
  param_deploy_production:
    default: false
    type: boolean

orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.12

jobs:
  package_2_build:
    working_directory: ~/package_2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build package_2
          command: just build


workflows:

  build_and_test:
    when:
      and:
        - not: << pipeline.parameters.param_deploy_production >>
    jobs:
      - package_2_build:
          context:
            - context-dev
            - slack-context