version: 2.1

parameters:
  param_deploy_production:
    default: false
    type: boolean

orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.22

jobs:
  app2_build:
    working_directory: ~/app_2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app2
          command: just build

  app2_deploy_pre_steps:
    working_directory: ~/app_2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app2
          command: just pre_deploy

  app2_deploy_dev:
    working_directory: ~/app_2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app2
          command: just deploy_dev

  app2_deploy_prod:
    working_directory: ~/app_2
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app2
          command: just deploy_prod

workflows:
  deploy_dev:
    when:
      and:
        - not: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app2_deploy_pre_steps:
          context:
            - context-dev
            - slack-context
      - app2_deploy_dev:
          requires:
            - app2_deploy_pre_steps
          context:
            - context-dev
            - slack-context

  deploy_prod:
    when: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app2_deploy_pre_steps:
          context:
            - context-prod
            - slack-context
      - app2_deploy_prod:
          requires:
            - app2_deploy_pre_steps
          context:
            - context-prod
            - slack-context

  build_and_test:
    when:
      and:
        - not: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app2_build:
          context:
            - context-dev
            - slack-context