
circle-ci-props:
  parameters:
    param_deploy_production:
      default: false
      type: boolean

  orbs:
    node: circleci/node@5.0.3

jobs:
  - app2-build:
      just-depends-on-type: build
      working_directory: ~/app_2
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Build app2
            command: just build
  - app2-deploy:
      just-depends-on-type: deploy
      working_directory: ~/app_2
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Build app2
            command: just build


workflow:
  build:
    just-depends-on-type: build
    jobs:
      - app2-build-step-1:
          context:
            - context-1
            - slack-context

  deploy:
    just-depends-on-type: deploy
    jobs:
      - app2-deploy-step-1:
          context:
            - context-1
            - slack-context