version: 2.1

parameters:
  param_deploy_production:
    default: false
    type: boolean

orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.12

jobs:
  app1_build_pre_steps:
    working_directory: ~/app_1
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Pre-Build app1
          command: just pre_build
  app1_build:
    working_directory: ~/app_1
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app1
          command: just build

  app1_deploy_dev:
    working_directory: ~/app_1
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app1
          command: just deploy_dev

  app1_deploy_prod:
    working_directory: ~/app_1
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build app1
          command: just deploy_prod

workflows:
  deploy_dev:
    when:
      and:
        - not: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app1_deploy_dev:
          context:
            - context-dev
            - slack-context

  deploy_prod:
    when: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app1_deploy_prod:
          context:
            - context-prod
            - slack-context

  build_and_test:
    when:
      and:
        - not: << pipeline.parameters.param_deploy_production >>
    jobs:
      - app1_build_pre_steps:
          context:
            - context-dev
            - slack-context
      - app1_build:
          requires:
            - app1_build_pre_steps
          context:
            - context-dev
            - slack-context