
circle-ci-props:
  orbs:
    node: circleci/node@5.1.3

jobs:
  - package-1-build:
      just-depends-on-type: build
      working_directory: ~/package_1
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Build package-1
            command: just build


workflow:
  build:
    just-depends-on-type: build
    jobs:
      - package-1-build:
          context:
            - context-1
            - slack-context
