#!/usr/bin/env just --justfile

build:
    yarn && yarn build

upload:
    echo "upload package_1"

deploy:
    echo "NOOP upload package_1"

test:
    echo "NOOP test package_1"

package:
    echo "NOOP package package_1"