#!/usr/bin/env just --justfile

build:
    yarn && yarn build

upload:
    echo "upload package_0"

deploy:
    echo "NOOP upload package_0"

test:
    echo "NOOP test package_0"

package:
    echo "NOOP package package_0"